name: edi
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  gsheets: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/addspendpage.png
    - assets/images/Grow more.png
    - assets/images/welcomepage.png
    - assets/images/bgcolor.png
    - assets/images/backg.png